static const char black[]       = "#1e222a";
static const char gray2[]       = "#2e323a"; // unfocused window border
static const char gray3[]       = "#545862";
static const char gray4[]       = "#6d8dad";
static const char blue[]        = "#61AFEF"; // focused window border
static const char green[]       = "#98C379";
static const char red[]         = "#E06C75";
static const char orange[]      = "#E49263";
static const char yellow[]      = "#E5C07B";
static const char pink[]        = "#E98CA4";
static const char purple[]      = "#C678DD";
static const char cyan[]        = "#56B6C2";
static const char col_borderbar[]  = "#1e222a"; // inner border
